#!/bin/bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew update

brew install \
docker
git
gpg
homebrew/dupes/rsync \

# Install some apps
brew install caskroom/cask/brew-cask
brew cask install \
1password \
android-file-transfer \
backblaze \
dropbox \
firefox \
google-chrome \
osxfuse \
packer \
parallels-desktop \
parallels-virtualization-sdk \
skype \
teamviewer \
utorrent \
vagrant \
virtualbox \
viscosity \
vlc \
xquartz
