#!/bin/bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew update

# Install some apps
brew install caskroom/cask/brew-cask
brew cask install <<END
1password
android-file-transfer
backblaze
firefox
google-chrome
skype
teamviewer
utorrent
viscosity
vlc
xquartz
END
